name: temporal
on:
  schedule:
    - cron: "*/10 * * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: new file every 10 minutes
        run: | 
          filename=$(date +%H-%M)
          timestamp=$(date +'%B %d, %y at %H:%M')
          cp ./.template ./$filename.md
          sed -i "s/XXX/$timestamp/g" ./$filename.md 
